---
- name: Include OS and distribution specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - always

- name: Include common install tasks
  include_tasks: "common/install.yml"
  tags:
    - install

- name: Include common config tasks
  include_tasks: "common/config.yml"
  tags:
    - config

- name: Include common launch tasks
  include_tasks: "common/launch.yml"
  tags:
    - launch

- name: Include common ssh-agent tasks
  include_tasks: "common/ssh-agent.yml"
  tags:
    - ssh-agent
