---
######### OpenSSH Authorized Keys (authorized_keys) configuration rendering

- name: Ensure existence of users to manage
  user:
    name: "{{ item }}"
  with_items: "{{ config.authorized_keys.keys() }}"
  become: true
  when: config.authorized_keys is not none

- name: Ensure existence of users (to manage) home SSH directories
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
  with_items: "{{ config.authorized_keys.keys() }}"
  become: true
  when: config.authorized_keys is not none

- name: Copy user authorized_keys configuration in place
  template:
    src: authorized_keys.j2
    dest: "/home/{{ item }}/.ssh/{{ authorized_keys_file }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  vars:
    account: "{{ item }}"
  with_items: "{{ config.authorized_keys.keys() }}"
  become: true
  when: config.authorized_keys is not none
