---
######### OpenSSH Authorized Keys (authorized_keys) configuration rendering

- name: Ensure existence of users to manage
  user:
    name: "{{ item.key }}"
  with_dict: "{{ ssh_config.authorized_keys }}"
  become: true
  when: ssh_config.authorized_keys is defined and ssh_config.authorized_keys is not none

- name: Ensure existence of users (to manage) home SSH directories
  file:
    path: "/home/{{ item.key }}/.ssh"
    state: directory
  with_dict: "{{ ssh_config.authorized_keys }}"
  become: true
  when: ssh_config.authorized_keys is defined and ssh_config.authorized_keys is not none

- name: Copy user authorized_keys configuration in place
  template:
    src: authorized_keys.j2
    dest: "/home/{{ item.key }}/.ssh/{{ authorized_keys_file }}"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: 0644
    backup: true
  vars:
    account: "{{ item.key }}"
  with_dict: "{{ ssh_config.authorized_keys }}"
  become: true
  when: ssh_config.authorized_keys is defined and ssh_config.authorized_keys is not none
