---
######### OpenSSH client (ssh_config) configuration rendering

- name: Copy custom global ssh_config configuration in place
  template:
    src: "{{ client_config_file }}.j2"
    dest: "{{ global_config_dir }}/{{ client_config_file }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  vars:
    account: global
  become: true
  when: config.client and "global" in config.client

- name: Copy user ssh_config configuration in place
  template:
    src: "{{ client_config_file }}.j2"
    dest: "/home/{{ item }}/.ssh/{{ client_config_file }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  vars:
    account: "{{ item }}"
  with_items: "{{ config.client.keys() | difference(['global']) }}"
  become: true
