---
######### OpenSSH known_hosts ([ssh_]known_hosts) configuration rendering

- name: Check that the global SSH known hosts file exists
  stat:
    path: "{{ global_config_dir }}/{{ global_knownhosts_file }}"
  register: stat_result

- name: backup original known hosts configuration prior to applying automation
  command: |
    mv "{{ global_config_dir }}/{{ global_knownhosts_file }}" "{{ global_config_dir }}/{{ global_knownhosts_file }}.bak"
  become: true
  when: stat_result.stat.exists

- name: Copy custom global known hosts configuration in place
  template:
    src: known_hosts.j2
    dest: "{{ global_config_dir }}/{{ global_knownhosts_file }}"
    owner: root
    group: root
    mode: 0644
  vars:
    account: global
  become: true
  when: config.known_hosts is not none and "global" in config.known_hosts

- name: Copy user known hosts configuration in place
  template:
    src: known_hosts.j2
    dest: "/home/{{ item }}/.ssh/{{ user_knownhosts_file }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  vars:
    account: "{{ item }}"
  with_items: "{{ config.known_hosts.keys() | difference(['global']) }}"
  become: true
  when: config.known_hosts is not none
