---
- name: Copy custom global known hosts configuration in place
  become: true
  template:
    src: known_hosts.j2
    dest: "{{ global_config_dir }}/{{ global_knownhosts_file }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  vars:
    account: global
  when: ssh_config.known_hosts is defined and "global" in ssh_config.known_hosts

- name: Copy user known hosts configuration in place
  become: true
  template:
    src: known_hosts.j2
    dest: "/home/{{ item }}/.ssh/{{ user_knownhosts_file }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
    backup: true
  vars:
    account: "{{ item }}"
  with_items: "{{ ssh_config.known_hosts.keys() | difference(['global']) }}"
  when: ssh_config.known_hosts is defined and ssh_config.known_hosts.keys() | difference(['global']) | length > 0
