---
######### OpenSSH service (sshd_config) configuration rendering

- name: Copy sshd_config configuration in place
  template:
    src: "{{ service_config_file }}.j2"
    dest: "{{ global_config_dir }}/{{ service_config_file }}"
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  become: true
  notify:
    - restart SSH daemon
