---
- name: Ensure existence of users to manage
  become: true
  user:
    name: "{{ item.key }}"
  with_dict: "{{ ssh_config.user_identities }}"
  when: ssh_config.user_identities is defined and ssh_config.user_identities.keys() | length > 0

- name: Ensure existence of users (to manage) home SSH directories
  become: true
  file:
    path: "/home/{{ item.key }}/.ssh"
    state: directory
  with_dict: "{{ ssh_config.user_identities }}"
  when: ssh_config.user_identities is defined and ssh_config.user_identities.keys() | length > 0

- name: Copy user private identities from local controller host in place on remote
  become: true
  copy:
    src: "{{ item.value.src }}"
    dest: "/home/{{ item.key }}/.ssh/{{ item.value.dest|default(item.value.src)|basename }}"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: '0644'
  with_dict: "{{ ssh_config.user_identities }}"
  when: ssh_config.user_identities is defined and ssh_config.user_identities.keys() | length > 0

- name: Copy user public identities from local controller host in place on remote
  become: true
  copy:
    src: "{{ item.value.src }}.pub"
    dest: "/home/{{ item.key }}/.ssh/{{ item.value.dest|default(item.value.src)|basename }}.pub"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: '0644'
  with_dict: "{{ ssh_config.user_identities }}"
  when: ssh_config.user_identities is defined and ssh_config.user_identities.keys() | length > 0
