---
- name: Ensure existence of users to manage
  user:
    name: "{{ item.key }}"
    group: "{{ item.key }}"
  with_dict: "{{ auto_enable_agent }}"
  become: true
  when: auto_enable_agent is not none

- name: Ensure existence of user shell profile file
  file:
    path: "/home/{{ item.key }}/.bash_profile"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: 0644
    state: touch
  with_dict: "{{ auto_enable_agent }}"
  become: true
  when: auto_enable_agent is not none

- name: Ensure user shell has an environment variable for the ssh-auth socket
  lineinfile:
    path: "/home/{{ item.key }}/.bash_profile"
    line: 'export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"'
    state: present
  with_dict: "{{ auto_enable_agent }}"
  become: true
  when: auto_enable_agent is not none

- name: Ensure existence of users systemd config directory
  file:
    path: "/home/{{ item.key }}/.config/systemd/user"
    state: directory
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
  with_dict: "{{ auto_enable_agent }}"
  become: true
  when: auto_enable_agent is not none

- name: Render user controlled ssh-agent service file
  template:
    src: ssh-agent.service.j2
    dest: "/home/{{ item.key }}/.config/systemd/user/ssh-agent.service"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: 0644
    backup: true
  vars:
    owner: "{{ item.key }}"
    run_args: "{{ item.value.run_args }}"
  with_dict: "{{ auto_enable_agent }}"
  become: true
  when: auto_enable_agent is not none
